// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjRXGF0FaQVgoIsiPsNSJ66SKRCX0as9E',
    appId: '1:395390859467:web:2d8def24aa7a3959b2434e',
    messagingSenderId: '395390859467',
    projectId: 'vastraloka-50290',
    authDomain: 'vastraloka-50290.firebaseapp.com',
    storageBucket: 'vastraloka-50290.appspot.com',
    measurementId: 'G-CDPN42ECBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzvI0-R8hnu-hMDN2Yse2UMn8yAW3mXvw',
    appId: '1:395390859467:android:3ee15f2140261d35b2434e',
    messagingSenderId: '395390859467',
    projectId: 'vastraloka-50290',
    storageBucket: 'vastraloka-50290.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPlm1fkMhrg_tv3j0KsdmDM-NbBc1GxFI',
    appId: '1:395390859467:ios:00da554e208536d7b2434e',
    messagingSenderId: '395390859467',
    projectId: 'vastraloka-50290',
    storageBucket: 'vastraloka-50290.appspot.com',
    iosBundleId: 'com.example.vastraloka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPlm1fkMhrg_tv3j0KsdmDM-NbBc1GxFI',
    appId: '1:395390859467:ios:00da554e208536d7b2434e',
    messagingSenderId: '395390859467',
    projectId: 'vastraloka-50290',
    storageBucket: 'vastraloka-50290.appspot.com',
    iosBundleId: 'com.example.vastraloka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjRXGF0FaQVgoIsiPsNSJ66SKRCX0as9E',
    appId: '1:395390859467:web:3bcbf77263fb2f91b2434e',
    messagingSenderId: '395390859467',
    projectId: 'vastraloka-50290',
    authDomain: 'vastraloka-50290.firebaseapp.com',
    storageBucket: 'vastraloka-50290.appspot.com',
    measurementId: 'G-C92XG5R06C',
  );
}
